apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: krishisetu
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: password
  MONGO_URI: mongodb+srv://krishisetu:Shashank+123@cluster0.ml1sv9w.mongodb.net/krishisetu?appName=Cluster0
