apiVersion: v1
kind: Service

metadata:
  name: {{ .Chart.Name }}-service
  namespace: krishisetu

spec:

  type: {{ .Values.service.type }}

  selector:
    app: {{ .Chart.Name }}

  ports:

  - port: {{ .Values.service.port }}

    targetPort: 5000
